apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: vitalsync-backend
spec:
  type: ClusterIP
  selector:
    app: vitalsync-backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
